### ISSUE TITLE
biblio_token_info() warning messages

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-contrib/biblio#13]
After installing Biblio, Multifield and Field Group, I am getting warnings when I "save" after editing or when visiting certain pages unrelated to biblio (but not always). Example when they do appear:

![biblio_errors](https://user-images.githubusercontent.com/78069725/153072921-3d046494-893a-4571-9dca-998daaf2b40f.png)

I have not created any biblio content yet.  There does not appear to be a biblio configuration page.  However, I did add a tab to the default biblio content type with a few term reference fields (picture below). I do not know if the warning happened before the new fields were added.

![biblio_create](https://user-images.githubusercontent.com/78069725/153072940-fb0cb1c9-8c19-4e28-969e-adc7de642c4b.png)

**Comment by Radcliffe** [comment]
I will note that the file `biblio_tokens.inc` refers to the schema for the `biblio` table. This table does not exist in the Backdrop port, although it is defined in the original Drupal module. The absence of this table causes warnings under PHP 7.4, and critical errors (white screen of death) in PHP 8. I don't know how to fix the issue, since I don't know if the Backdrop port requires this table. But the errors go away if I remove the file `biblio_tokens.inc` or rename it to prevent it from being loaded.

**Comment by Radcliffe** [comment]
This seems to be related to #4

**Comment by jenlampton** [comment]
I have removed the token info because the field module should provide tokens since we are using field module fields. 
This fix is in the latest release: https://github.com/backdrop-contrib/biblio/releases/tag/1.x-2.0.1
