### ISSUE TITLE
Enabling the biblio module makes all pages in my system yield an error

### ISSUE THREAD

**Issue by gwolf** [backdrop-contrib/biblio#22]
Hello,
I am in the process of converting a Drupal7 site to Backdrop. I did most of the heavy-lifting using the D2B migrate module.
Only after doing so, I learnt the Biblio module was available for Backdrop as well, and installed it. However, after enabling the module, all web pages yielded an erorr: `array_diff_key(): Argument #1 ($array) must be of type array, null given»` 
I don't see any errors or messages logged to the nginx log.
The system log report reports:

    TypeError: array_diff_key(): Argument #1 ($array) must be of type array, null given en array_diff_key() (línea 12 de /var/www/backdrop_backdrop.gwolf.org/modules/biblio/biblio.tokens.inc).

Please suggests how should I proceed!

**Comment by gwolf** [comment]
Just noted that, prior to the request that caused the error message to the system log I quoted, I also got a PHP warning:

    Warning: Trying to access array offset on value of type bool en biblio_token_info() (línea 12 de /var/www/backdrop_backdrop.gwolf.org/modules/biblio/biblio.tokens.inc).

Same line of the other message.

**Comment by klonos** [comment]
Hey @gwolf 👋🏼 ...as per the comments from others in [the Zulip thread you started](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Help!.20Stuck.20in.20migration.20from.20D7.3A.20biblio.20module.3F), this problem should be fixed in the dev version. Please try the dev version of the module, by downloading it from https://github.com/backdrop-contrib/biblio/archive/refs/heads/1.x-2.x.zip, and remember to report back if that fixes it for you.

**Comment by jenlampton** [comment]
This fix was included in https://github.com/backdrop-contrib/biblio/releases/tag/1.x-2.0.1, just released :tada
